"""Build the job-request / item-order seed from source_files/JOB_REQUEST_INVENTORY.xlsx.

Writes seed_data/jobs.json and supabase/seed/30_jobs.sql. Rows are tagged to the
"EXCEL-IMPORT" logger (they were not entered in the app).
"""
import json
from datetime import datetime
from pathlib import Path

import openpyxl

ROOT = Path(__file__).resolve().parent.parent
STATUS = {"PENDING": "Pending", "REQUEST FOR OFFER": "Request for offer", "APPROVED IN BC": "Approved in BC",
          "PO ISSUED": "PO issued", "CAPEX PO ISSUED": "CAPEX PO issued", "SUSPENDED": "Suspended",
          "JOB REQUEST ABANDONED": "Abandoned"}
EXEC = {"PENDING": "Pending", "IN PROGRESS": "In progress", "DONE": "Done"}


def s(v):
    if v is None:
        return None
    v = str(v).strip()
    return v or None


def d(v):
    return v.date().isoformat() if isinstance(v, datetime) else None


def main() -> None:
    wb = openpyxl.load_workbook(ROOT / "source_files/JOB_REQUEST_INVENTORY.xlsx", read_only=True, data_only=True)
    jobs = []
    for r in wb["JOB REQUEST"].iter_rows(values_only=True):
        r = r[1:14]
        if not isinstance(r[0], int) or not s(r[3]):
            continue
        jobs.append({"sn": r[0], "date": d(r[1]), "cs": s(r[2]), "desc": s(r[3]), "brk": s(r[4]),
                     "status": STATUS.get(s(r[5]) or "", "Pending") if s(r[5]) else "Pending",
                     "po": s(r[6]), "value": float(r[7]) if isinstance(r[7], (int, float)) else None,
                     "vendor": s(r[8]), "exec": EXEC.get(s(r[9]) or ""), "jcc": s(r[10]) == "YES",
                     "paid": s(r[11]) == "YES", "remarks": s(r[12])})
    orders = []
    for r in wb["ITEM ORDERS"].iter_rows(values_only=True):
        r = r[1:11]
        if not isinstance(r[0], int) or not (s(r[3]) or s(r[2])):
            continue
        items = s(r[3]) or s(r[1])  # a few rows have the description in the date column
        orders.append({"sn": r[0], "date": d(r[1]), "mrs": s(r[2]), "items": items, "prn": s(r[4]),
                       "status": STATUS.get(s(r[5]) or "", "Pending") if s(r[5]) else "Pending",
                       "po": s(r[6]), "value": float(r[7]) if isinstance(r[7], (int, float)) else None,
                       "vendor": s(r[8]), "remarks": s(r[9])})
    data = {"jobs": jobs, "orders": orders}
    (ROOT / "seed_data/jobs.json").write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    blob = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    (ROOT / "supabase/seed/30_jobs.sql").write_text(
        "-- Generated by scripts/build_jobs_seed.py from source_files/JOB_REQUEST_INVENTORY.xlsx\n"
        f"select public.load_job_data($json${blob}$json$::jsonb);\n", encoding="utf-8")
    print(f"{len(jobs)} job requests, {len(orders)} item orders")


if __name__ == "__main__":
    main()
