"""Build the PM task library seed from seed_data/pm_task_library.csv (CHIENGUTRG08).

Equipment names are mapped to asset codes through the PM aliases in
seed_data/master_data.json (run scripts/build_seed.py first). Names without an
alias stay unmapped (asset null) for the owner to map in Admin.

Writes seed_data/pm_tasks.json and supabase/seed/20_pm_tasks.sql.
"""
import csv
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FREQ = {"Daily": "daily", "Weekly": "weekly", "Monthly": "monthly", "Quarterly": "quarterly",
        "Bi-Annually": "bi_annual", "Annually": "annual"}


def norm(s: str) -> str:
    return re.sub(r"\s+", " ", s.strip().rstrip(".").strip()).upper()


def main() -> None:
    master = json.loads((ROOT / "seed_data/master_data.json").read_text(encoding="utf-8"))
    alias = {}
    area = {}
    for a in master["assets"]:
        area[a["code"]] = a.get("area") or "U1"
        for src, name in a.get("aliases", []):
            if src == "pm_register":
                alias[norm(name)] = a["code"]

    texts: list[str] = []
    index: dict[str, int] = {}
    tasks = []
    unmapped = set()
    with open(ROOT / "seed_data/pm_task_library.csv", newline="", encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            eq = row["equipment_name_in_register"].strip()
            code = alias.get(norm(eq))
            if not code:
                unmapped.add(eq)
            ids = []
            for t in (x.strip() for x in row["tasks"].split("|")):
                if not t:
                    continue
                if t not in index:
                    index[t] = len(texts)
                    texts.append(t)
                ids.append(index[t])
            m = re.search(r"(\d[\d,]*)\s*(?:running\s*)?hours?\b", row["tasks"], re.I)
            tasks.append({"f": FREQ[row["frequency"]], "sn": int(row["register_sn"]), "eq": eq, "asset": code,
                          "area": area.get(code, "U1"), "t": ids,
                          "h": int(m.group(1).replace(",", "")) if m else None})

    data = {"texts": texts, "tasks": tasks}
    (ROOT / "seed_data/pm_tasks.json").write_text(json.dumps(data, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    blob = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    (ROOT / "supabase/seed/20_pm_tasks.sql").write_text(
        "-- Generated by scripts/build_pm_seed.py from seed_data/pm_task_library.csv\n"
        f"select public.load_pm_tasks($json${blob}$json$::jsonb);\n", encoding="utf-8")
    print(f"{len(tasks)} PM tasks, {len(texts)} distinct task texts, {len(unmapped)} equipment names unmapped:")
    for u in sorted(unmapped):
        print("  -", u)


if __name__ == "__main__":
    main()
