-- Pick-lists from the 603-001 Utility Downtime Analysis Template (seed_data/downtime_master_lists.json).
create table public.lists (
  list_name text not null,
  value     text not null,
  parent    text,
  sort      integer not null default 0,
  active    boolean not null default true,
  primary key (list_name, value)
);

alter table public.lists enable row level security;
create policy lists_read on public.lists for select to authenticated using (true);
create policy lists_admin_write on public.lists for all to authenticated using (public.has_role('admin', 'section_manager')) with check (public.has_role('admin', 'section_manager'));
revoke all on public.lists from anon;

insert into public.lists (list_name, value, parent, sort) values
  ('failure_category', 'Mechanical', null, 1),
  ('failure_mode', 'Bearing failure', 'Mechanical', 1),
  ('failure_mode', 'Mechanical seal / gasket leakage', 'Mechanical', 2),
  ('failure_mode', 'Coupling failure', 'Mechanical', 3),
  ('failure_mode', 'Impeller / rotor damage', 'Mechanical', 4),
  ('failure_mode', 'Belt failure or slippage', 'Mechanical', 5),
  ('failure_mode', 'Valve failure (passing / stuck)', 'Mechanical', 6),
  ('failure_mode', 'Pipe or line leakage', 'Mechanical', 7),
  ('failure_mode', 'Excessive vibration / misalignment', 'Mechanical', 8),
  ('failure_mode', 'Tube leakage', 'Mechanical', 9),
  ('failure_mode', 'Fan / blower fault', 'Mechanical', 10),
  ('failure_mode', 'Gearbox fault', 'Mechanical', 11),
  ('failure_mode', 'General mechanical wear', 'Mechanical', 12),
  ('failure_mode', 'Lubrication failure', 'Mechanical', 13),
  ('failure_category', 'Electrical', null, 2),
  ('failure_mode', 'Motor failure / burnt winding', 'Electrical', 14),
  ('failure_mode', 'Public power (PHCN) outage', 'Electrical', 15),
  ('failure_mode', 'Generator changeover failure', 'Electrical', 16),
  ('failure_mode', 'Contactor / relay fault', 'Electrical', 17),
  ('failure_mode', 'Cable or wiring fault', 'Electrical', 18),
  ('failure_mode', 'VFD / soft starter fault', 'Electrical', 19),
  ('failure_mode', 'Overload trip', 'Electrical', 20),
  ('failure_mode', 'Panel / circuit breaker fault', 'Electrical', 21),
  ('failure_mode', 'Earth fault', 'Electrical', 22),
  ('failure_mode', 'Capacitor / power factor fault', 'Electrical', 23),
  ('failure_mode', 'Voltage fluctuation', 'Electrical', 24),
  ('failure_category', 'Instrumentation and Control', null, 3),
  ('failure_mode', 'Sensor / transmitter fault', 'Instrumentation and Control', 25),
  ('failure_mode', 'PLC or controller fault', 'Instrumentation and Control', 26),
  ('failure_mode', 'HMI / display fault', 'Instrumentation and Control', 27),
  ('failure_mode', 'Pressure switch fault', 'Instrumentation and Control', 28),
  ('failure_mode', 'Level control fault', 'Instrumentation and Control', 29),
  ('failure_mode', 'Temperature control fault', 'Instrumentation and Control', 30),
  ('failure_mode', 'Solenoid valve fault', 'Instrumentation and Control', 31),
  ('failure_mode', 'Calibration drift', 'Instrumentation and Control', 32),
  ('failure_mode', 'Communication / signal loss', 'Instrumentation and Control', 33),
  ('failure_mode', 'Flow meter fault', 'Instrumentation and Control', 34),
  ('failure_mode', 'Safety interlock trip', 'Instrumentation and Control', 35),
  ('failure_category', 'Process and Utility', null, 4),
  ('failure_mode', 'Low feed water supply', 'Process and Utility', 36),
  ('failure_mode', 'Poor raw water quality', 'Process and Utility', 37),
  ('failure_mode', 'High conductivity / TDS', 'Process and Utility', 38),
  ('failure_mode', 'Steam pressure drop', 'Process and Utility', 39),
  ('failure_mode', 'Low condensate return', 'Process and Utility', 40),
  ('failure_mode', 'Refrigerant loss / low charge', 'Process and Utility', 41),
  ('failure_mode', 'Low chilled water flow', 'Process and Utility', 42),
  ('failure_mode', 'Compressed air pressure drop', 'Process and Utility', 43),
  ('failure_mode', 'Fouling / scaling', 'Process and Utility', 44),
  ('failure_mode', 'Chemical dosing failure', 'Process and Utility', 45),
  ('failure_mode', 'Cooling tower fouling', 'Process and Utility', 46),
  ('failure_mode', 'Air / gas locking', 'Process and Utility', 47),
  ('failure_mode', 'Resin exhaustion', 'Process and Utility', 48),
  ('failure_mode', 'Membrane fouling', 'Process and Utility', 49),
  ('failure_category', 'Operational', null, 5),
  ('failure_mode', 'Operator error', 'Operational', 50),
  ('failure_mode', 'Delayed start-up / shutdown', 'Operational', 51),
  ('failure_mode', 'Improper changeover', 'Operational', 52),
  ('failure_mode', 'Delayed response to alarm', 'Operational', 53),
  ('failure_mode', 'Manpower shortage', 'Operational', 54),
  ('failure_mode', 'Wrong parameter setting', 'Operational', 55),
  ('failure_category', 'Maintenance and Spares', null, 6),
  ('failure_mode', 'Spare parts unavailable', 'Maintenance and Spares', 56),
  ('failure_mode', 'Awaiting vendor / OEM support', 'Maintenance and Spares', 57),
  ('failure_mode', 'Awaiting CAPEX approval', 'Maintenance and Spares', 58),
  ('failure_mode', 'Extended repair duration', 'Maintenance and Spares', 59),
  ('failure_mode', 'Repeat failure / poor previous repair', 'Maintenance and Spares', 60),
  ('failure_mode', 'Tooling unavailable', 'Maintenance and Spares', 61),
  ('failure_category', 'Planned Maintenance', null, 7),
  ('failure_mode', 'Planned preventive maintenance', 'Planned Maintenance', 62),
  ('failure_mode', 'Statutory / insurance inspection', 'Planned Maintenance', 63),
  ('failure_mode', 'Boiler chemical cleaning / blowdown', 'Planned Maintenance', 64),
  ('failure_mode', 'Descaling / de-fouling', 'Planned Maintenance', 65),
  ('failure_mode', 'Major overhaul', 'Planned Maintenance', 66),
  ('failure_mode', 'Plant-wide shutdown', 'Planned Maintenance', 67),
  ('failure_mode', 'Installation / upgrade project', 'Planned Maintenance', 68),
  ('failure_mode', 'Calibration exercise', 'Planned Maintenance', 69),
  ('failure_category', 'External Factors', null, 8),
  ('failure_mode', 'Utility supply failure', 'External Factors', 70),
  ('failure_mode', 'LPFO / gas supply shortage', 'External Factors', 71),
  ('failure_mode', 'Diesel supply shortage', 'External Factors', 72),
  ('failure_mode', 'Weather / environmental event', 'External Factors', 73),
  ('failure_mode', 'Vendor / contractor delay', 'External Factors', 74),
  ('failure_mode', 'Production hold (no demand)', 'External Factors', 75),
  ('issue_description', 'Equipment failed to start', null, 1),
  ('issue_description', 'Equipment tripped during operation', null, 2),
  ('issue_description', 'Equipment shut down on alarm', null, 3),
  ('issue_description', 'Fault code displayed on HMI / panel', null, 4),
  ('issue_description', 'Abnormal noise observed', null, 5),
  ('issue_description', 'Excessive vibration observed', null, 6),
  ('issue_description', 'Overheating observed', null, 7),
  ('issue_description', 'Leakage observed', null, 8),
  ('issue_description', 'Low output pressure', null, 9),
  ('issue_description', 'Low output flow', null, 10),
  ('issue_description', 'High discharge temperature', null, 11),
  ('issue_description', 'Pressure fluctuation', null, 12),
  ('issue_description', 'Flow fluctuation', null, 13),
  ('issue_description', 'Loss of power to equipment', null, 14),
  ('issue_description', 'Motor overload trip', null, 15),
  ('issue_description', 'Emergency stop activated', null, 16),
  ('issue_description', 'Low water level alarm', null, 17),
  ('issue_description', 'High water level alarm', null, 18),
  ('issue_description', 'Water carryover observed', null, 19),
  ('issue_description', 'Foaming in boiler observed', null, 20),
  ('issue_description', 'Low steam pressure', null, 21),
  ('issue_description', 'Steam leakage observed', null, 22),
  ('issue_description', 'Condensate not returning', null, 23),
  ('issue_description', 'Compressed air pressure below set point', null, 24),
  ('issue_description', 'Moisture in compressed air line', null, 25),
  ('issue_description', 'Dew point out of specification', null, 26),
  ('issue_description', 'Chilled water temperature above set point', null, 27),
  ('issue_description', 'Refrigerant low pressure alarm', null, 28),
  ('issue_description', 'Cooling tower fan not running', null, 29),
  ('issue_description', 'Poor water quality at outlet', null, 30),
  ('issue_description', 'High conductivity / TDS at outlet', null, 31),
  ('issue_description', 'Turbidity above limit', null, 32),
  ('issue_description', 'UV lamp failure alarm', null, 33),
  ('issue_description', 'Filter differential pressure high', null, 34),
  ('issue_description', 'Pump not priming / loss of suction', null, 35),
  ('issue_description', 'Pump running dry', null, 36),
  ('issue_description', 'Borehole yield dropped', null, 37),
  ('issue_description', 'Tank level low', null, 38),
  ('issue_description', 'Tank overflow', null, 39),
  ('issue_description', 'Scheduled maintenance carried out', null, 40),
  ('issue_description', 'Statutory inspection carried out', null, 41),
  ('issue_description', 'Equipment isolated for repairs', null, 42),
  ('issue_description', 'Equipment on standby (not required)', null, 43),
  ('issue_description', 'Equipment awaiting spare parts', null, 44),
  ('issue_description', 'Equipment awaiting vendor attention', null, 45),
  ('issue_description', 'Other (describe in Remarks)', null, 46),
  ('downtime_type', 'Unplanned Breakdown', null, 1),
  ('downtime_type', 'Planned Maintenance', null, 2),
  ('downtime_type', 'External Supply Failure', null, 3),
  ('downtime_type', 'Idle / Standby', null, 4),
  ('attended_by', 'Utility Section (In-house)', null, 1),
  ('attended_by', 'Electrical & Instrumentation Section', null, 2),
  ('attended_by', 'Automation Section', null, 3),
  ('attended_by', 'R&A Section', null, 4),
  ('attended_by', 'General Workshop', null, 5),
  ('attended_by', 'External Vendor', null, 6),
  ('production_impact', 'Full Stoppage', null, 1),
  ('production_impact', 'Partial / Reduced Output', null, 2),
  ('production_impact', 'Standby Unit Took Over', null, 3),
  ('production_impact', 'No Production Impact', null, 4),
  ('downtime_status', 'Open', null, 1),
  ('downtime_status', 'In Progress', null, 2),
  ('downtime_status', 'Awaiting Spares', null, 3),
  ('downtime_status', 'Awaiting CAPEX Approval', null, 4),
  ('downtime_status', 'Awaiting Vendor', null, 5),
  ('downtime_status', 'Closed', null, 6),
  ('category_6m', 'Man (people / skill / manning)', null, 1),
  ('category_6m', 'Machine (equipment / design)', null, 2),
  ('category_6m', 'Material (spares / consumables / water quality)', null, 3),
  ('category_6m', 'Method (procedure / practice)', null, 4),
  ('category_6m', 'Measurement (instrumentation / calibration)', null, 5),
  ('category_6m', 'Environment (external / ambient / supply)', null, 6),
  ('action_type', 'Immediate Fix Only', null, 1),
  ('action_type', 'Repair + Procedure Change', null, 2),
  ('action_type', 'Preventive Maintenance Revision', null, 3),
  ('action_type', 'Spare Parts Stocking', null, 4),
  ('action_type', 'Training / Competence', null, 5),
  ('action_type', 'Equipment Modification', null, 6),
  ('action_type', 'CAPEX - New Equipment', null, 7),
  ('action_type', 'CAPEX - Equipment Upgrade', null, 8),
  ('action_type', 'Vendor / Contract Change', null, 9),
  ('rca_status', 'Not Started', null, 1),
  ('rca_status', 'Investigation Ongoing', null, 2),
  ('rca_status', 'Root Cause Identified', null, 3),
  ('rca_status', 'Action In Progress', null, 4),
  ('rca_status', 'Awaiting CAPEX Approval', null, 5),
  ('rca_status', 'Completed - Pending Verification', null, 6),
  ('rca_status', 'Closed - Verified Effective', null, 7)
on conflict do nothing;
